# #Tuck "new line" inside the ($all) variable
# format = """($all
# )$character"""
#
# # No new line between shell prompts
# add_newline = false
#
# # No line-break between shell prompts
# [line_break]
# disabled = true# # ~/.config/starship.toml
# [î‚¶](fg:#0e0e0e)\
format = """\
[  ](fg:#0e0e0e bg:#0e0e0e)\
$username\
[î‚´](fg:#0e0e0e bg:#141414)\
$directory\
[î‚´](fg:#141414 bg:#252525)\
$git_branch\
$git_status\
[î‚´](fg:#252525 bg:#2e2e2e)\
$all\
$cmd_duration\
$jobs\
$battery\
$time\
$character"""
# [î‚´](fg:#2e2e2e bg:#2e2e2e)\

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "fg:#ffffff bg:#0e0e0e"
style_root = "fg:#ff7eb6 bg:#0e0e0e"
format = '[ó±—† ]($style)' # $user

[directory]
style = "fg:#dde1e6 bg:#141414"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = "ï€• ~"
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ğŸœ "
"Pictures" = "ï‘† "
"Videos" = "ï€½ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[git_branch]
symbol = "ï˜"
style = "fg:#42be65 bg:#252525"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = "fg:#42be65 bg:#252525"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"
format = '[$all_status$ahead_behind ]($style)'

[sudo]
symbol = 'î«² '
style = "fg:#ee5396 bg:#2e2e2e"
disabled = true
format='[ $symbol]($style)'

[aws]
symbol = "îŒ½ "
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[conda]
symbol = "ï„Œ"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[dart]
symbol = "î˜"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[c]
symbol = "î˜"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = "î‰µ"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[elm]
symbol = "î˜¬"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[golang]
symbol = "ó°Ÿ“"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[haskell]
symbol = "Î»"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[java]
symbol = "î‰–"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[julia]
symbol = "î˜¤"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[lua]
symbol = "î˜ "
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[dotnet]
symbol = "î™ˆ"
style = "fg:#3ddbd9 bg:#2e2e2e"
# heuristic = false
format = '[ $symbol ($version )(î¿ $tfm )]($style)'

[nim]
symbol = "ó°†¥"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[nix_shell]
symbol = "ï‹œ"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = "î‰"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[bun]
symbol = "î¯"
style = "fg:#ffe97b bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[perl]
symbol = "î©"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[php]
symbol = "î˜ˆ"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[python]
symbol = "î˜†"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[ruby]
symbol = "îˆ¾"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[rust]
symbol = "îš‹"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[swift]
symbol = "ó°›¥"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = '[ $symbol ($version )]($style)'

[package]
symbol = "ó°—"
style = "fg:#3ddbd9 bg:#2e2e2e"
format = "[ $symbol $version]($style)"
disabled = true


[cmd_duration]
min_time = 1
style = "fg:#ffe97b bg:#2e2e2e"
format = "[ $duration]($style)"
disabled = true

[jobs]
symbol = "ó°™’"
style = "fg:#ffe97b bg:#2e2e2e"
format = "[ $symbol]($style)"

[battery]
full_symbol = "ó°¹ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó°‚ƒ "
unknown_symbol = "ó°½ "
empty_symbol = "ó°‚ "
format = "[ $symbol$percentage ]($style bg:#2e2e2e)"
disabled = true

[[battery.display]]
threshold = 15
style = "bold fg:#ff7eb6"

[[battery.display]]
threshold = 50
style = "fg:#ffe97b"

[[battery.display]]
threshold = 101
style = "bold #42be65"

# Prompt: optional param 1
[time]
disabled = true
time_format = "%R"
style = "bg:#3b4363"
format = '[î‚´](fg:#2e2e2e $style)[ ó°« $time ](fg:#94e2d5 $style)'

# Last param in the first line/row
# fg:#3b4363 if time enabled
[character]
success_symbol = "[î‚´ ](fg:#2e2e2e)"
error_symbol = "[îƒ† ](fg:#2e2e2e)"
